### ISSUE TITLE
Rails error after installing this css.

### ISSUE THREAD

**Issue by manshu** [mkhairi/bootswatch-sass#1]
Undefined mixin 'gradient-vertical-three-colors'.

Extracted source (around line #3):
@import 'variables';
@mixin btn-shadow($color){
  @include gradient-vertical-three-colors(lighten($color, 8%), $color, 60%, darken($color, 4%));
  filter: none;
  border-bottom: 1px solid darken($color, 10%);
}

**Comment by mkhairi** [comment]
hi @manshu, did you include bootstrap-sass in your gem file? bootstrap-sass gem is required for this gem.

**Comment by manshu** [comment]
yes, i figured it out. It was the asset pipeline error. I had to manually setup the the pipeline.
