### ISSUE TITLE
missing custom.min.css?

### ISSUE THREAD

**Issue by ybakos** [mkhairi/bootswatch-sass#2]
When using the v4 [bootstrap][1] gem and the [bootstrap-sass][2] gem, I have to manually create an _assets/stylesheets/custom.min.css_ [copied from the official _bootswatch_ source][3] in order for any bootswatch stylesheet to appear correctly. Is this a flaw in the _boostrap-sass_ gem, or is the flaw mine?

With the _Gemfile_:

    gem 'bootstrap'
    gem 'bootswatch'
    source 'https://rails-assets.org' do
      gem 'rails-assets-tether', '>= 1.3.3'
    end

and the _assets/stylesheets/application.css.sass_:

    @import "bootswatch/cosmo/variables"
    @import "bootstrap"
    @import "bootswatch/cosmo/bootswatch"

and the _assets/javascripts/application.js_:

    //= require jquery
    //= require tether
    //= require bootstrap-sprockets
    //= require jquery_ujs
    //= require turbolinks
    //= require_tree .

and the layout _app/views/layouts/application.html.haml_ (excuse the haml):

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

Not all the necessary styles seems to exist such that the example matches the app. Here is the difference:

[![enter image description here][4]][4]

> Left: official example. Right: the Rails app in question

If I manually create _assets/stylesheets/custom.min.css_, add a `stylesheet_link_tag` for `custom.min.css` and the necessary `Rails.application.config.assets.precompile` directive, the application matches the example.

[![enter image description here][5]][5]

> Left: official example. Right: the Rails app in question

Neither the bootswatch documentation nor the bootstrap-sass documentation mention anything about this magic _custom.min.css_ file. All of the bootswatch examples use a link to this stylesheet. Is this a flaw in the documentation for bootswatch, a flaw in the bootswatch-sass gem, or a flaw in my understanding of how all these moving parts should be made to work?

  [1]: https://github.com/twbs/bootstrap-rubygem
  [2]: https://github.com/mkhairi/bootswatch-sass
  [3]: https://github.com/thomaspark/bootswatch/blob/gh-pages/assets/css/custom.min.css
  [4]: https://i.stack.imgur.com/0bZGq.png
  [5]: https://i.stack.imgur.com/O50J6.png

**Comment by woutervanranst** [comment]
I don't agree with the close reason of #636; there is a difference (see screenshots that ybakos mentioned)
example: the custom.min.css specifies addtl padding for the .h1 tag
