### ISSUE TITLE
Just a question 

### ISSUE THREAD

**Issue by david-dacruz** [mkhairi/bootswatch-sass#3]
Hi thanks for writing and sharing this usefull gem I just ave a small question I was able to follow your steps to install bootswatch scss but now I'm wondering if I require bootsrap js in my application ? it's not specified in you readme. thanks ahead. David.

**Comment by mkhairi** [comment]
yeah, it still need to require js for full bootstrap experience. sorry for the quick start readme. already update for better instruction. 🙇

**Comment by david-dacruz** [comment]
It's awsome no problem I just added the require it works very easy and it's great I'll definitely recommend this gem around thanks for writing this :wink:
