### ISSUE TITLE
update to bootswatch v4.3.1

### ISSUE THREAD

**Issue by m5o** [mkhairi/bootswatch-sass#5]
Hi @mkhairi 👋

Could you please update repo and gem 🤓

* update to bootswatch v4.3.1

see: https://github.com/thomaspark/bootswatch/commit/f42e9299c01cb800d99f6664e20363dc1859c6b9

**Comment by mkhairi** [comment]
@m5o, v4.3.1 published 🙇

**Comment by m5o** [comment]
✨ Awesome ✨
